services:
  - type: web
    name: kericho-voting
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 24
